# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f94e19aca088d7270c7b87fdbb58382fd067ed457adc5ed8c1689eca82ecd789529acdd1e0843bae6feb064c20b7e6eb78c066ed54cd89130e05c1449d32a592

test:
  secret_key_base: e6146f4139ca40501babe46273d6ce22243bb064b72c73f005a40b0f76080e9f437b548026fdc336cb56674e312703d05a47fd7e3dcc2c62e6103d3d118a7969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
